# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85cef2fa32bc35c37a1224713cf3a725210d8ec959de1b63cd75e18c5005b4aa8c69504e52808b7f73c9590ff666dd7b61df70b27d0498771da3969316deb0e5

test:
  secret_key_base: 8d9817087e77607da81145393e56de857e14ada5472345cd87e6d1c665fa54f78096979860b9b288253b7f30caee0fa7a3830af8e9af7f102f1e9d8df48eda8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
